name: brims
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.5
  path: ^1.9.0
  provider: ^6.1.5+1
  get_it: ^9.1.0
  shadcn_flutter: ^0.0.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.4

flutter:
  uses-material-design: true
